### ISSUE TITLE
Cannot set headers of a response

### ISSUE THREAD

**Issue by shalzz** [dollarshaveclub/cloudworker#127]
Hi, 

According to the cloudflare docs and example snippets we should be able to change the headers of a response for caching. see:
https://developers.cloudflare.com/workers/templates/snippets/alter_headers/

But with cloudworker trying to do the same results in an error: 
`TypeError: Can't modify immutable headers`

**Comment by RamIdeas** [comment]
Why was this closed?

I have a deployed worker proxying files from s3 -- but s3 doesn't seem to set the Content-Type header for SVG files correctly, so I manually set the header on the response and it works fine

Just got my worker running locally with this project and ran into this `TypeError: Can't modify immutable headers` error...

Edit: turns out s3 now sends the correct content-type so this isn't as big of a problem for me but still don't think it is something blocked in cloudflare's environment

**Comment by xbaha** [comment]
i have the same problem, did you find a solution? I need to set content-type

**Comment by RamIdeas** [comment]
The solution is just to clone the response/headers and then modify the headers as you wish

But when running on cloudflare, cloning will be a waste
