### ISSUE TITLE
v0.1.0-beta.2 not published to npm

### ISSUE THREAD

**Issue by hankjacobs** [dollarshaveclub/cloudworker#92]
This issue tracks my inability to publish v0.1.0-beta.2 to npm. I'm working on getting that fixed. I will close this issue once fixed and version published.

**Comment by hankjacobs** [comment]
Still unable to publish, still working on fixing that.

**Comment by defjosiah** [comment]
Hi! Thanks for an awesome package, just wondering if you were able to get this straightened out?
We use a "await request.dispatch" pattern in our tests, and unfortunately since we added a "event.waitUntil" to the main worker code those tests broke.

From the code changes in this release, it looks like the v0.1.0-beta.2 would fix this.

**Comment by hankjacobs** [comment]
Just pushed it! Thank you for your patience.

**Comment by defjosiah** [comment]
Thank you!
